# Example configuration file for a EAGLE-XL-like simulation

# Location of your other .yml files that are passed to the
# velociraptor auto plotter (these describe your scaling)
# relation figures. Also required is the registration file
# in the case where you have non-catalogue properties
# used in the autoplotter.
auto_plotter_directory: auto_plotter
auto_plotter_registration: registration.py

# Location of the 'observational data' repository and its compiled
# contents.
observational_data_directory: ../observational_data

# Style sheet to be used throughout with plotting
matplotlib_stylesheet: mnras.mplstyle

# Jinja2 template that gets fed the swiftsimio metadata
# object for you to describe the run with.
description_template: description.html

# Location and description of additional figures
scripts:
  - filename: scripts/density_temperature.py
    caption: Density-temperature diagram.
    output_file: density_temperature.png
    section: Density-Temperature
    title: Density-Temperature
  - filename: scripts/density_temperature_metals.py
    caption: Density-temperature diagram with the pixel value weighted by the mean logrithmic metal mass fraction (absolute) in that bin. Medians are not used due to their computational complexity.
    output_file: density_temperature_metals.png
    section: Density-Temperature
    title: Density-Temperature (Metals)
  - filename: scripts/density_internal_energy.py
    caption: Density-Internal Energy diagram.
    output_file: density_internal_energy.png
    section: Density-Temperature
    title: Density-Internal Energy
  - filename: scripts/density_pressure.py
    caption: Density-pressure diagram.
    output_file: density_pressure.png
    section: Density-Temperature
    title: Density-Pressure
  - filename: scripts/star_formation_history.py
    caption: Star formation history plotted directly from the SFR.txt file produced by SWIFT.
    output_file: star_formation_history.png
    section: Star Formation History
    title: Star Formation History
  - filename: scripts/stellar_mass_evolution.py
    caption: Evolution of the stellar mass plotted directly from the statistics.txt file produced by SWIFT.
    output_file: stellar_mass_evolution.png
    section: Star Formation History
    title: Stellar Mass Evolution
  - filename: scripts/metallicity_distribution.py
    caption: Metal mass fraction distribution shown for each simulation; solid lines show gas metallicity and dashed lines show the same for the stars.
    output_file: metallicity_distribution.png
    section: Metal Mass Fractions
    title: Metal Mass Fraction Distribution
  - filename: scripts/birth_density_f_E.py
    caption: Feedback energy fractions $f_E$ shown against the birth densities for the stars. Any variation here is due to differing metallicity of the gas.
    section: Stellar Feedback
    title: $f_E$ as a Function of Birth Density
    output_file: birth_density_f_E.png
  - filename: scripts/birth_density_distribution.py
    caption: Distributions of birth densities, split by redshift.
    title: Stellar Birth Densities
    section: Stellar Feedback
    output_file: birth_density_distribution.png
  - filename: scripts/birth_density_metallicity.py
    caption: Birth density-metallicity plane. Contour lines show stars formed at all epochs, with the background color map showing the feedback energy fraction associated with this particle's feedback event.
    title: Birth Density-Metallicity Plane
    section: Stellar Feedback
    output_file: birth_density_metallicity.png
  - filename: scripts/gas_metallicity_evolution.py
    caption: Evolution of the metal mass in gas per unit co-moving volume.
    output_file: gas_metallicity_evolution.png
    section: Metal Evolution
    title: Gas Phase Metal Mass Density Evolution
  - filename: scripts/star_metallicity_evolution.py
    caption: Evolution of the metal mass locked in stars per unit co-moving volume.
    output_file: star_metallicity_evolution.png
    section: Metal Evolution
    title: Metal Mass Locked in Stars Density Evolution
  - filename: scripts/bh_metallicity_evolution.py
    caption: Evolution of the metal mass locked in black holes per unit co-moving volume.
    output_file: bh_metallicity_evolution.png
    section: Metal Evolution
    title: Metal Mass Locked in Black Holes Density Evolution
  - filename: scripts/bh_accretion_evolution.py
    caption: Evolution of the accretion rate onto BHs per unit co-moving volume.
    output_file: bh_accretion_evolution.png
    section: Black Holes Evolution
    title: Black Hole Accretion History
  - filename: scripts/bh_mass_evolution.py
    caption: Evolution of the BH mass per unit co-moving volume.
    output_file: bh_mass_evolution.png
    section: Black Holes Evolution
    title: Black Hole Mass History
  - filename: scripts/bh_masses.py
    caption: Relation between black hole particle (dynamical) masses and subgrid masses. The vertical dashed lines shows the primordial gas particle mass and the horizontal dashed lines corresponds to the black hole seed mass.
    output_file: bh_masses.png
    section: Black Holes
    title: Black Hole Dynanmical and Subgrid Masses
  - filename: scripts/gas_masses.py
    caption: Gas Particle Masses with the threshold for splitting indicated by the vertical dashed line.
    output_file: gas_masses.png
    section: Histograms
    title: Gas Particle Masses
  - filename: scripts/gas_smoothing_lengths.py
    caption: Gas Particle Comoving Smoothing Lengths with the minimal smoothing length indicated by the vertical dashed line.
    output_file: gas_smoothing_lengths.png
    section: Histograms
    title: Gas Particle Smoothing Lengths
  - filename: scripts/max_temperatures.py
    caption: Maximal temperature recorded by gas particles throughout the entire simulation.
    output_file: gas_max_temperatures.png
    section: Histograms
    title: Maximal Temperature reached by gas particles
  - filename: scripts/feedback_SNII_events.py
    caption: Number of stellar feedback events recorded by gas particles throughout the entire simulation.
    output_file: gas_num_SNII_events.png
    section: Histograms
    title: Number of stellar feedback events 
  - filename: scripts/feedback_AGN_events.py
    caption: Number of AGN feedback events recorded by gas particles throughout the entire simulation.
    output_file: gas_num_AGN_events.png
    section: Histograms
    title: Number of AGN feedback events
  - filename: scripts/particle_updates_step_cost.py
    caption: Wall-clock time to run a time-step as a function of the number of gas particles updated. The tracks at the top correspond to steps where the tree is rebuilt, i/o is performed, FoF is run or other non-regular operations are done.
    title: Wall-clock time per gas particle updates.
    section: Run Performance
    output_file: particle_updates_step_cost.png
  - filename: scripts/wallclock_simulation_time.py
    caption: The cosmic time as a function of the wall-clock time.
    title: Cosmic time vs. wall-clock time
    section: Run Performance
    output_file: wallclock_simulation_time.png
  - filename: scripts/wallclock_number_of_steps.py
    caption: The cumulative number of the simulation time-steps as a function of the wall-clock time.
    title: The number of steps vs. wall-clock time
    section: Run Performance
    output_file: wallclock_number_of_steps.png
  - filename: scripts/simulation_time_number_of_steps.py
    caption: The cumulative number of the simulation time-steps as a function of the cosmic time.
    title: Number of steps vs. cosmic time
    section: Run Performance
    output_file: simulation_time_number_of_steps.png
  - filename: scripts/wallclock_timebin_hist.py
    caption: Total wall-clock time spent in each of the different simulation time-bins.
    title: Wall-clock time per time-bin
    section: Run Performance
    output_file: wallclock_timebin_hist.png
  - filename: scripts/hot_gas_plots.py
    caption: X-ray luminosity - Halo mass.
    output_file: hgas_Lx.png
    section: Hot gas properties
    title: X-ray luminosity
  - filename: scripts/dummy.py
    caption: Hot gas pressure profiles of galaxy groups.
    output_file: hgas_P_P500_r.png
    section: Hot gas properties
    title: Pressure profiles
  - filename: scripts/dummy.py
    caption: Hot gas density profiles of galaxy groups.
    output_file: hgas_rho_r.png
    section: Hot gas properties
    title: Density profiles
  - filename: scripts/dummy.py
    caption: Hot gas entropy profiles of galaxy groups.
    output_file: hgas_S_S500_r.png
    section: Hot gas properties
    title: Entropy profiles
  - filename: scripts/dummy.py
    caption: Local SZ flux−halo mass relation.
    output_file: hgas_tSZ.png
    section: Hot gas properties

